# Generated by Django 2.1.2 on 2018-10-16 02:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181015_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceyears',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='years',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], max_length=100, verbose_name='Ano de conecades: '),
        ),
        migrations.DeleteModel(
            name='ChoiceYears',
        ),
    ]
