# Generated by Django 2.1.2 on 2018-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181015_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='years',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ano de conecades: '),
        ),
    ]
