# Generated by Django 2.1.2 on 2018-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181016_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='years',
        ),
        migrations.AddField(
            model_name='user',
            name='qnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quanto(a)s vezes você foi no Conecades:'),
        ),
    ]
